resilience4j:

  circuitbreaker:
    instances:
      redisCircuitBreaker:
        sliding-window-type: time_based
        sliding-window-size: 30
        failure-rate-threshold: 10
        minimum-number-of-calls: 10
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 10
        slow-call-duration-threshold: 300ms
        slow-call-rate-threshold: 50
        record-exceptions:
          - org.springframework.data.redis.RedisConnectionFailureException
          - org.springframework.data.redis.RedisSystemException
          - io.lettuce.core.RedisCommandTimeoutException
          - io.lettuce.core.RedisException
      dataSender:
        sliding-window-type: time_based
        sliding-window-size: 60
        failure-rate-threshold: 50
        minimum-number-of-calls: 10
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 10
        slow-call-duration-threshold: 500ms
        slow-call-rate-threshold: 50
        record-exceptions:
          - java.util.concurrent.TimeoutException
          - java.lang.IllegalStateException
    circuit-breaker-aspect-order: 1
  timelimiter:
    instances:
      dataSender:
        timeout-duration: 1000ms
        cancel-running-future: true
    time-limiter-aspect-order: 3

---
spring:
  config:
    activate:
      on-profile: local, test

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: qa

---
spring:
  config:
    activate:
      on-profile: prd
